# Generated by Django 5.0 on 2026-05-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0003_alter_school_options_alter_customuser_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name="Canteen's Name")),
                ('is_open', models.BooleanField(default=True, verbose_name='Open')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canteen', to='auths.school', verbose_name='School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name="Dish's name")),
                ('description', models.TextField(blank=True, verbose_name='Description and Composition')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калории')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Фото блюда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='canteen.foodcategory')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Date Menu')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='canteen.canteen')),
                ('dishes', models.ManyToManyField(related_name='daily_menus', to='canteen.dish', verbose_name="Today's dishes")),
            ],
            options={
                'unique_together': {('canteen', 'date')},
            },
        ),
    ]
