# Generated by Django 5.0 on 2026-05-05 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(max_length=1000, verbose_name='Comment')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('daily_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='canteen.dailymenu', verbose_name='Daily Menu')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='canteen.dish', verbose_name='Dish')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='canteen.dailymenu', verbose_name='Daily Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_reactions', to='canteen.reactiontype', verbose_name='Reaction')),
            ],
            options={
                'verbose_name': 'Menu Reaction',
                'verbose_name_plural': 'Menu Reactions',
            },
        ),
        migrations.CreateModel(
            name='DishReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='canteen.dish', verbose_name='Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_reactions', to='canteen.reactiontype', verbose_name='Reaction')),
            ],
            options={
                'verbose_name': 'Dish Reaction',
                'verbose_name_plural': 'Dish Reactions',
            },
        ),
        migrations.AddConstraint(
            model_name='menureaction',
            constraint=models.UniqueConstraint(fields=('user', 'daily_menu'), name='unique_menu_reaction_per_user'),
        ),
        migrations.AddConstraint(
            model_name='dishreaction',
            constraint=models.UniqueConstraint(fields=('user', 'dish'), name='unique_dish_reaction_per_user'),
        ),
    ]
