# Generated by Django 5.0 on 2026-05-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='School',
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_at'], 'verbose_name': 'School', 'verbose_name_plural': 'School'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='companies',
            new_name='schools',
        ),
    ]
