# Generated by Django 5.0 on 2026-05-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_rename_company_school_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_at'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(help_text='School the user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auths.school', verbose_name='School'),
        ),
    ]
